// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDqim3nV5INbJOjPyAE5T1XB_V_2oSsJg',
    appId: '1:594366773091:web:60d793883fc11f3ae5c556',
    messagingSenderId: '594366773091',
    projectId: 'finx-aff21',
    authDomain: 'finx-aff21.firebaseapp.com',
    storageBucket: 'finx-aff21.firebasestorage.app',
    measurementId: 'G-NYV9N3DH3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr_gxAp0KHlv9cuidvbKphYLtQnOlxkJo',
    appId: '1:594366773091:android:788c1c702e1d95b1e5c556',
    messagingSenderId: '594366773091',
    projectId: 'finx-aff21',
    storageBucket: 'finx-aff21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa6w7TOHhXmbmBK4OsCKiAYHBkkgmIN88',
    appId: '1:594366773091:ios:bf7e79c876d65031e5c556',
    messagingSenderId: '594366773091',
    projectId: 'finx-aff21',
    storageBucket: 'finx-aff21.firebasestorage.app',
    iosBundleId: 'com.example.finx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa6w7TOHhXmbmBK4OsCKiAYHBkkgmIN88',
    appId: '1:594366773091:ios:bf7e79c876d65031e5c556',
    messagingSenderId: '594366773091',
    projectId: 'finx-aff21',
    storageBucket: 'finx-aff21.firebasestorage.app',
    iosBundleId: 'com.example.finx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDqim3nV5INbJOjPyAE5T1XB_V_2oSsJg',
    appId: '1:594366773091:web:01ae8060a873219ce5c556',
    messagingSenderId: '594366773091',
    projectId: 'finx-aff21',
    authDomain: 'finx-aff21.firebaseapp.com',
    storageBucket: 'finx-aff21.firebasestorage.app',
    measurementId: 'G-9YNQNSCBEK',
  );
}
